### ISSUE TITLE
Auth won't be stored

### ISSUE THREAD

**Issue by JacksWastedLife** [dsdevbe/ldap-connector#11]
I've implemented ldap-connector successfully in Laravel 4.3 and now I'm trying to do so in Laravel 5. I've used the login template that ships with a new Laravel app and I've overwritten the postLogin method from AuthenticatesAndRegistersUsers in my AuthController by overwrite the required 'email' input to 'username'.

The Auth::attempt works fine and returns true when using correct credentials, but after the intended redirect the Auth doesn't seems to be stored, because a Auth::check() returns false, so I'm reredirected to auth/login.

I've tested my session config by adding something to the session, delete that statement and echo the session value after a few redirects. Works like a charm.

**Comment by max-me** [comment]
Same problem. I tried to investigate and found that every time you reload a page, Laravel it trying to find user by calling retrieveById() method that is not implemented in this package

**Comment by JacksWastedLife** [comment]
Nice to know that I'm not the only one with this issue! :)
Do you know any workarounds? We're can I find the retrieveById() maybe I could implement the missing method in this package and contribue to it?

Thanks!

**Comment by max-me** [comment]
Thank you for contributing! The only thing to add is that this solution will only work if you set admin_user account in your config

**Comment by dsdevbe** [comment]
Indeed that's correct. This will be added asap included with some refactoring and tests.
