### ISSUE TITLE
User Null

### ISSUE THREAD

**Issue by omarjmv** [dsdevbe/ldap-connector#5]
how can the user is null? or default

**Comment by dsdevbe** [comment]
Hello,

Is it possible to give a bit more detail.
Thanks in advance.

**Comment by omarjmv** [comment]
need not be necessary to have a user to check the other users ... like you can leave this option null Thank you

**Comment by dsdevbe** [comment]
The ldap-connector is currently using the lib `Adldap` to perform the ldap queries on the active directory. The settings configured in `Ldap.php` will be passed to the `Adldap`.

You can remove the default username/password in the `Ldap.php`file but like they say on the library documentation page "It is strongly recommended to add an admin username/password, as a standard domain user account will not have many permissions to query over Active Directory". [AdLdap User Configuration](https://github.com/adldap/adLDAP/wiki/Configuration-Settings#user-authentication)

I will update the documentation of 'Ldap-Connector' that the admin user is optional.
